#! /bin/bash

#pushd `dirname $0` > /dev/null
#localdir=`pwd -P`
#popd > /dev/null
#
#command=". $localdir/bashrc"
#
#touch ~/.bashrc
#if ! grep "$command" ~/.bashrc; then
#  chmod 755 "$localdir/scripts"
#  echo                                                  >> ~/.bashrc
#  echo "# Charge les composantes globales du bashrc"    >> ~/.bashrc
#  echo "if [ -f $localdir/bashrc ]; then"               >> ~/.bashrc
#  echo "  $command"                                     >> ~/.bashrc
#  echo "fi"                                             >> ~/.bashrc
#fi

if ! grep zsh /etc/shells > /dev/null; then
 echo "trzzz"
else
  echo "azerty"
fi 
