#! /bin/bash

pushd `dirname $0` > /dev/null
localdir=`pwd -P`
popd > /dev/null

command=". $localdir/zsh/zshrc"

touch ~/.zshrc
if ! grep "$command" ~/.zshrc > /dev/null ; then
  chmod 755 "$localdir/scripts"
  echo                                                  >> ~/.zshrc
  echo "# Charge les composantes globales du zshrc"     >> ~/.zshrc
  echo "if [ -f $localdir/zsh/zshrc ]; then"            >> ~/.zshrc
  echo "  $command"                                     >> ~/.zshrc
  echo "fi"                                             >> ~/.zshrc
fi
