#!/bin/bash

# /!\ You must already be in current directory for this to work /!\

# Chargement des définitions
if [ -f definitions ]; then
  source definitions
fi

# # on affiche le logo
# if shopt -q login_shell; then
#   echo ".globalrc version" $(cat $GLOBALRC/version)
#   cat "$GLOBALRC/logo"
# fi

# Chargement des aliases
if [ -f aliases ]; then
  source aliases
fi

# Chargement des functions
if [ -f functions ]; then
  source functions
fi

# Ajoute les scripts aux programmes par défaut
if [ -d "$(pwd)/scripts" ]; then
  PATH="$PATH:$GLOBALRC/scripts"
fi
