#!/bin/bash

# /!\ You must already be in current directory for this to work /!\

# Chargement des définitions
if [ -f definitions ]; then
  source definitions
fi

# Chargement des functions
if [ -f functions ]; then
  source functions
fi

# Login shell
if (running_shell zsh && [[ -o login ]]) || (running_shell bash && shopt -q login_shell); then

#  echo ".globalrc version" $(cat $GLOBALRC/version)
  # on affiche le logo
  cat logo
fi

# Chargement des aliases
if [ -f aliases ]; then
  source aliases
fi
