#!/bin/bash
# Script to handle i3 operations such as locking, rebooting, etc...

lock() {

    # cf: https://stackoverflow.com/a/45985000/5771067
    # This selects a png file randomly across a directory structure
    # NB : If no file is found, the globbing pattern is passed as-is to
    # i3lock. Not an issue, since i3lock gracefully ignores it.
    shopt -s globstar
    files=(Pictures/lockscreen/**/*.png)

    i3lock --color 000000 --image "${files[RANDOM % ${#files[@]}]}" --ignore-empty-password --show-failed-attempts &> ~/log.txt
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
