#! /bin/bash

# Copyright csdt


# Add scripts to $PATH
if [ -d "$(pwd)/scripts" ] ; then
  PATH="$(pwd)/scripts:$PATH"
fi

if [ -x /usr/bin/most ]; then
  export PAGER="/usr/bin/most"
fi

if [ -x /usr/bin/vim ]; then
  export EDITOR="vim"
fi

# Use custom inputrc
export INPUTRC="$GLOBALRC/../templates/inputrc"

# Use custom sshrc location
export SSHHOME="$GLOBALRC/sshrc"

# Make agent-forwarding work even when reattaching screen/tmux
# NB : In case of multiple simultaneous connections with ssh agent forwarding
# to the same server as the same user, only the last to connect can be used
# cf : https://superuser.com/questions/180148/how-do-you-get-screen-to-automatically-connect-to-the-current-ssh-agent-when-re/424588#424588
# Note that since we skip if it this is already a symlink, it notably won't change in case of sudo -sE
if [ -S "$SSH_AUTH_SOCK" ] && [ ! -h "$SSH_AUTH_SOCK" ]; then
  ln -sf "$SSH_AUTH_SOCK" "{{ ssh_auth_sock }}"
  export SSH_AUTH_SOCK="{{ ssh_auth_sock }}"
fi

# ls extra colors
LS_COLORS="$LS_COLORS*.JPG=01;35:*.GIF=01;35:*.jpg=01;35:*.gif=01;35:*.jpeg=01;35:*.pcx=01;35:*.png=01;35:*.pnm=01;35:*.bz2=01;31:*.mpg=01;38:*.mpeg=01;38:*.MPG=01;38:*.MPEG=01;38:*.m4v=01;038:*.mp4=01;038:*.swf=01;038:*.avi=01;38:*.AVI=01;38:*.wmv=01;38:*.WMV=01;38:*.asf=01;38:*.ASF=01;38:*.mov=01;38:*.MOV=01;38:*.mp3=01;39:*.ogg=01;39:*.MP3=01;39:*.Mp3=01;39"

