#!/bin/zsh
# Places you into current directory
pushd $(dirname $0) > /dev/null

# Loading common components
if [ -f ../commonrc ]; then
  pushd .. > /dev/null
  source commonrc
  popd > /dev/null
fi

# Try to switch to a 256-color terminal
# Can be cancelled setting the $DISABLE_256_COLORS variable to anything
if [ -z $DISABLE_256_COLORS ]; then
  source 256colors
fi

# Custom functions definition
source definitions

# TODO: Stop hardcoding that, do it in a cleaner way
POWERLINE_ROOT="$HOME/.local/lib/python2.7/site-packages"
POWERLINE_PATH="$POWERLINE_ROOT/powerline/bindings/zsh/powerline.zsh"
export PATH="$HOME/.local/bin:$PATH"
export XDG_CONFIG_DIRS="$GLOBALRC/zsh/xdg_config/"
if [[ -a $POWERLINE_PATH ]]; then
  powerline-daemon -q
  . $POWERLINE_PATH
else
  # Loading prompt
  source prompt
fi

# Completion initialization, should be run as late as possible
source compinit

# Miscellaneous conf (including parts from gmrl)
source config

# Start zplug plugin manager
source zplug


# Key mappings common to several keymaps
keymap_list=('viins' 'vicmd' 'visual')

for keymap in $keymap_list; do
  # Aliasing movement keys (With Alt) to arrow keys
  # NB: It is nice to do that instead of mapping directly to the corresponding
  # zle widgets, to avoid having to manually which widget is the correct one
  # See http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html
  bindkey -M $keymap -s '^[{{ key_rh_left  }}' '^[[D'
  bindkey -M $keymap -s '^[{{ key_rh_down  }}' '^[[B'
  bindkey -M $keymap -s '^[{{ key_rh_up    }}' '^[[A'
  bindkey -M $keymap -s '^[{{ key_rh_right }}' '^[[C'
done

# Comes back into previous directory
popd > /dev/null
