#! /bin/bash

# This script transforms a LDAP acces via PAM in a local access.
# Be careful using it, it could break LDAP access.

pushd `dirname $0` > /dev/null
source ../bash/functions

LdapUid=`id -u`
Username=`id -u -n`

if [ $LdapUid = 0 ] ; then
  echo "Do not run this script as root (but you need sudo access)"
else
  if cat /etc/passwd | grep $Username > /dev/null ; then
    echo "You already have a local account, there's no need to create one"
  else
    # We use this trick to keep sudo access during the script, but we need to be
    # careful escaping variables, etc ...
    tempfile="/tmp/ldap-to-local-$UID-$$-$RANDOM"
    echo "

      # Function to ask confirmation
      confirm() {
        if [[ \$2 ]]; then
          if [[ \$2 == 'y' ]]; then
            space='[Y/n]'
          elif [[ \$2 == 'n' ]]; then
            space='[y/N]'
          else
            error 'Confirmation must have y or n as default value'
          fi
        else
          space='[y/n]'
        fi      
      
        while true; do
          read -n 1 -p \"\$1 \$space \" on
      
          # default value
          if [[ \$on == '' && \$2 ]]; then
            on=\$2
          else
            echo
          fi
      
          case \$on in
            [Yy]* )
              return 0
              ;;
            [Nn]* )
              return 1
              ;;
          esac
        done
      }

      echo 'Deactivating LDAP ...'
      sed --in-place=.bak 's/ldap//' /etc/nsswitch.conf
      echo 'Erasing names cache ...'
      service nscd restart && nscd -i passwd
      echo 'Creating new local user ...'
      adduser $Username
      adduser $Username sudo
      nscd -i passwd
      LocalUid=\`id -u $Username\`
      echo 'Changing file permissions in $HOME ...'
      chown -R $Username: $HOME
      echo \"Done. If you owned files in other places than $HOME, you might need to run something like :
      \\\`find / -uid $LdapUid -exec chown \$LocalUid {} \\\`
      LDAP uid : $LdapUid
      Local uid : \$LocalUid \"
      echo 'You might also need to do something about your gid'
      echo 'Reactivating LDAP ...'
      cp /etc/nsswitch.conf.bak /etc/nsswitch.conf
      echo 'Restarting daemons'
      service nscd restart
      service nslcd restart
      echo 'Done. Everything should be okay now'
      
      if ! confirm 'Do you want to go on a rescue root shell ?' 'n' ; then
        exit
      fi
      " > $tempfile
    sudo bash --rcfile $tempfile
    rm -f $tempfile
  fi
fi

popd > /dev/null
