#! /bin/bash

# Usage
function usage
{
  echo 'Envoie la configuration à tous les hosts présents dans ssh_config'
  echo 'usage: pushrc_ssh [-d remote-directory]'
}

# Confirm
function confirm() {
if [[ "$2" ]]; then
  if [[ "$2" == "o" ]]; then
    space="[O/n]"
  elif [[ "$2" == "n" ]]; then
    space="[o/N]"
  else
    error "La confirmation doit avoir 'o' ou 'n' pour valeur par défaut"
  fi
else
  space="[o/n]"
fi      

while true; do
  read -n 1 -p "$1 $space " on

  # default value
  if [[ "$on" == "" && "$2" ]]; then
    on=$2
  else
    echo
  fi

  case $on in
    [Oo]* )
      return 0
      ;;
    [Nn]* )
      return 1
      ;;
  esac
done
}


# Main

localdir=""

while [ "$1" != "" ]; do
  case $1 in
    -d )                    shift
      localdir="-d $1 "
      ;;
    -h | --help )           usage
      unset localdir
      exit
      ;;
    * )                     break
      ;;
  esac
  shift
done

echo "Envoi multiple de configuration"
echo
echo

for i in `grep 'Host ' $GLOBALRC/ssh_config | awk '{print $2}'`; do
  confirm "Envoyer la configuration sur $i ?" o && pushrc $localdir$i
done

echo
echo
echo "Envoi de la configuration terminé"

unset localdir
