#! /bin/sh

# Grouping prevents the script to bug when overwritten
{

  VERSION="0.1"

  . "$GLOBALRC/lib.sh/stream.sh"
  . "$GLOBALRC/lib.sh/sync.sh"

  # Params
  host=
  key_file=
  export_key=0
  use_master_co=1
  use_tar=1
  use_scp_trick=1
  use_compression=1
  port=

  #
  last_push=
  scp_pre_hooks=

  # Toggle hooks execution
  exec_local_pre_hook=1
  exec_local_post_hook=1
  exec_remote_pre_hook=1
  exec_remote_post_hook=1

  # compression control
  compression=

  # shell commands to execute on the remote machine to execute pre-sync hooks
  remote_pre_hook="$(generate_execute_hooks pre push)"
  # shell commands to execute on the remote machine to execute post-sync hooks
  remote_post_hook="$(generate_execute_hooks post push)"

  # print a little help
  print_usage () {
    echo "USAGE: $0 [--help|--version] [--verbose|--quiet|--fake] <hostname> [--master-co|--no-master-co] [--scp-trick|--no-scp-trick] [--compression|--no-compression] [--port portnumber] [--export-key [keyfile]|--no-export-key]"
  }

  # Export the ssh key to the host
  export_ssh_key () {
    if [ ${export_key:-0} != 0 ]
    then
      if [ -z "$key_file" ]
      then
        info "  exporting the ssh key to $host${port:+:$port}"
        if ! fake ssh-copy-id ${port:+-p $port} "$host"
        then
          error "    Unable to export the key"
          return 1
        fi
        info "    ssh key successfully exported"
        [ -z "$masterco" ] && { ssh-add -l 2> /dev/null || fake ssh-add ; }
      else
        info "  exporting the ssh key  $key_file to $host${port:+:$port}"
        if ! fake ssh-copy-id ${port:+-p $port} "$host" -i "$key_file" > /dev/null
        then
          error "    Unable to export the key"
          return 1
        fi
        info "    ssh key successfully exported"
      fi
    fi
    return 0
  }

  # Copy files of GLOBALRC dir to remote
  copy_files () {
    local path hooks
    hooks=
    path="$( echo "${1:-.globalrc}" | sed 's/\s/\\&/g')"

    if [ ${scp_pre_hooks:-0} != 0 ]
    then
      hooks="$(echo "$remote_pre_hook") &&" # command substitution removes trailing endline
    fi

    info "  Copy files onto $host${port:+:$port}"
    if [ "${use_tar:-0}" != 0 ]
    then
      if tar_copy_to_remote
      then
        info "      Files successfully copied"
        return 0
      fi
      warning "      Error when using tar over ssh"
      warning "    Trying again with scp"
    fi
    if [ "${use_scp_trick:-0}" != 0 ]
    then
      FAKE_DISPLAY="scp -q $masterco $compression ${port:+-P $port} -r ${GLOBALRC_DIR}. $host":\'\"'$(echo "$GLOBALRC")'\"\'
      if fake scp -q $masterco $compression ${port:+-P $port} -r "$GLOBALRC_DIR". "$host":'"$('"$remote_source$hooks"'
          echo "${GLOBALRC:-.globalrc}"       # echo GLOBALRC dir for copy
        )"'
      then
        info "      Files successfully copied"
        return 0
      fi
      warning "      Error when using scp trick"
      warning "    Trying again without scp trick"

      # Execute pre hooks via a classic connexion
      if [ ${scp_pre_hooks:-0} != 0 ] && [ "${exec_remote_pre_hook:-0}" != 0 ]
      then
        info "    Executing pre-sync remote hook scripts"
        if ! hook_remote_pre_sync
        then
          error "      Error encountered while executing pre-sync remote hook scripts"
          return 1
        fi
        info "      Successful execution"
      fi
    fi

    if fake scp -q $masterco $compression ${port:+-P $port} -r "$GLOBALRC_DIR". "$host":"$path"
    then
      info "      Files successfully copied"
      return 0
    fi
    error "      Copy failed"
    return 1
  }

  hook_remote_pre_sync () {
    [ "${exec_remote_pre_hook:-0}" = 0 ] && return 0
    FAKE_DISPLAY="ssh $masterco $compression -T ${port:+-p $port} $host '"'"$GLOBALRC"/hooks/push-pre-sync && "$GLOBALRC"/hooks/pre-sync && "$GLOBALRC"/hooks/push-pre-copy'\'
    fake ssh $masterco $compression -T ${port:+-p $port} "$host" "$remote_source$remote_pre_hook"
  }

  # Execute hook scripts on both sides before copying files
  hook_pre_sync () {
    scp_pre_hooks=0
    # executing local hooks
    if [ "${exec_local_pre_hook:-0}" != 0 ]
    then
      info "    Executing pre-sync local hook scripts"
      if ! execute_hooks "$host" pre push
      then
        error "      Error encountered while executing pre-sync local hook scripts"
        warning "      Maybe you try to push your configuration on a mahcine without GLOBALRC"

        # It is hard to get the exit code of the piped command in a POSIX shell
        # so the best way is to not use the named stream error
        # promptyn "  Do you want to continue anyway? [Y/n]" Y | error
        promptyn "  Do you want to continue anyway? [Y/n]" Y >&2

        return $?
      fi
      info "      Successful execution"
    fi

    if [ "${exec_remote_pre_hook:-0}" != 0 ]
    then
      if [ -z "$masterco" -a ${use_scp_trick:-0} != 0 ]
      then
        warning "      No master connexion available"
        warning "      Remote hook scripts will be executed during the copy using the scp trick"
        return 0
      fi

      # executing remote hooks
      info "    Executing pre-sync remote hook scripts"
      if ! hook_remote_pre_sync
      then
        error "      Error encountered while executing pre-sync remote hook scripts"
        warning "      Maybe you try to push your configuration on a mahcine without GLOBALRC"

        # It is hard to get the exit code of the piped command in a POSIX shell
        # so the best way is to not use the named stream error
        # promptyn "  Do you want to continue anyway? [Y/n]" Y | error
        promptyn "  Do you want to continue anyway? [Y/n]" Y >&2

        return $?
      fi
      info "      Successful execution"
    fi
    return 0
  }

  # Execute hook scripts on both sides after copying files
  hook_post_sync () {
    # executing local hooks
    if [ "${exec_local_post_hook:-0}" != 0 ]
    then
      info "    Executing post-sync local hook scripts"
      if ! execute_hooks "$host" post push
      then
        error "      Error encountered while executing post-sync local hook scripts"
        return 1
      fi
      info "      Successful execution"
    fi

    # executing remote hooks
    if [ "${exec_remote_pre_hook:-0}" != 0 ]
    then
      info "    Executing post-sync remote hook scripts"
      FAKE_DISPLAY="ssh $masterco $compression -T ${port:+-p $port} $host '"'"$GLOBALRC"/hooks/push-post-copy && "$GLOBALRC"/hooks/post-sync && "$GLOBALRC"/hooks/push-post-sync'\'
      if ! fake ssh $masterco $compression -T ${port:+-p $port} "$host" "$remote_source$remote_post_hook"
      then
        error "      Error encountered while executing post-sync remote hook scripts"
        return 1
      fi
      info "      Successful execution"
    fi
    return 0
  }

  # Synchronize configuration from local to remote using a master connexion
  push_with_master () {
    info "Synchronize the local configuration to $host${port:+:$port}"
    if ! establish_master_co
    then
      push_without_master
      return $?
    fi


    if ! export_ssh_key
    then
      error "Aborting"
      close_master
      return 1
    fi

    info ""
    info "  Getting the remote GLOBALRC path"
    FAKE_DISPLAY="ssh $masterco $compression -T ${port:+-p $port} $host '"'echo "$GLOBALRC"'\' fake :
    remote_path="$([ -n "$FAKE" ] && echo "~/.globalrc" || ssh $masterco $compression -T ${port:+-p $port} "$host" "$remote_source"'
      # echo GLOBALRC dir
      echo "$GLOBALRC" ;
    ')"
    if [ -z "$remote_path" ]
    then
      warning "    Failed to get remote path"
      warning '    Assuming "~/.globalrc"'
      remote_path=".globalrc"
    else
      info "    Successfully got remote path ($remote_path)"
    fi

    if ! hook_pre_sync
    then
      error "Aborting"
      close_master
      return 1
    fi

    info ""
    if copy_files "$remote_path"
    then
      if ! hook_post_sync
      then
        close_master
        return 1
      fi
    else
      error "Aborting"
      close_master
      return 1
    fi

    info ""
    info "Synchronization was successful"
    info ""
    close_master
  }

  # Synchronize configuration from local to remote
  push_without_master () {
    info "Synchronize the local configuration to $host${port:+:$port}"

    if ! export_ssh_key
    then
      error "Aborting"
      return 1
    fi

    if ! hook_pre_sync
    then
      error "Aborting"
      return 1
    fi

    info ""
    if copy_files
    then
      if ! hook_post_sync
      then
        return 1
      fi
    else
      error "Aborting"
      return 1
    fi

    info ""
    info "Synchronization was successful"
    info ""
  }

  push () {
    local fail
    if [ -z "$host" ]
    then
      error "No hostname provided"
      return 1
    fi
    if [ ${use_compression:-0} != 0 ]
    then
      compression="-C"
    else
      compression=
    fi
    if [ ${use_master_co:-0} != 0 ]
    then
      push_with_master
    else
      push_without_master
    fi
    fail=$?
    host=
    port=
    if [ ${last_push:-0} = 0 ]
    then
      last_push=$fail
    fi
    return $fail
  }

  first_args=1
  require_first_args () {
    if [ ${first_args:-0} != 0 ]
    then
      return 0
    else
      error "$1 needs to be placed before any host options"
      error "Aborting"
      print_usage | error
      exit 1
    fi
  }

  while [ $# != 0 ]
  do
    arg="$1"
    shift
    case "$arg" in
      --local-pre-hook|--sender-pre-hook)      exec_local_pre_hook=1   ;;
      --local-post-hook|--sender-post-hook)    exec_local_post_hook=1  ;;
      --remote-pre-hook|--receiver-pre-hook)   exec_local_pre_hook=1   ;;
      --remote-post-hook|--receiver-post-hook) exec_remote_post_hook=1 ;;
      --no-local-pre-hook|--no-sender-pre-hook)      exec_local_pre_hook=0   ;;
      --no-local-post-hook|--no-sender-post-hook)    exec_local_post_hook=0  ;;
      --no-remote-pre-hook|--no-receiver-pre-hook)   exec_local_pre_hook=0   ;;
      --no-remote-post-hook|--no-receiver-post-hook) exec_remote_post_hook=0 ;;
      -s|--hooks)
        exec_local_pre_hook=1
        exec_local_post_hook=1
        exec_remote_pre_hook=1
        exec_remote_post_hook=1
        ;;
      -S|--no-hooks)
        exec_local_pre_hook=0
        exec_local_post_hook=0
        exec_remote_pre_hook=0
        exec_remote_post_hook=0
        ;;
      --local-hooks|--sender-hooks)
        exec_local_pre_hook=1
        exec_local_post_hook=1
        ;;
      --no-local-hooks|--no-sender-hooks)
        exec_local_pre_hook=0
        exec_local_post_hook=0
        ;;
      --remote-hooks|--receiver-hooks)
        exec_remote_pre_hook=1
        exec_remote_post_hook=1
        ;;
      --no-remote-hooks|--no-receiver-hooks)
        exec_remote_pre_hook=0
        exec_remote_post_hook=0
        ;;
      --pre-hooks)
        exec_local_pre_hook=1
        exec_remote_pre_hook=1
        ;;
      --post-hooks)
        exec_local_post_hook=1
        exec_remote_post_hook=1
        ;;
      -k|--export-key)
        export_key=1
        key_file=
        if [ -f "$1" ]
        then
          key_file="$1"
          shift
        fi
        first_args=0
        ;;
      -k=*|--export-key=*)
        export_key=1
        key_file="$(echo "$arg" | sed 's/^.*=//')"
        first_args=0
        ;;
      -K|--no-export-key)
        export_key=0
        key_file=
        first_args=0
        ;;
      -m|--master|--master-co)
        use_master_co=1
        first_args=0
        ;;
      -M|--no-master|--no-master-co)
        use_master_co=0
        first_args=0
        ;;
      -t|--scp-trick)
        use_scp_trick=1
        first_args=0
        ;;
      -T|--no-scp-trick)
        use_scp_trick=0
        first_args=0
        ;;
      --tar)
        use_tar=1
        first_args=0
        ;;
      --no-tar)
        use_tar=0
        first_args=0
        ;;
      -c|--compression)
        use_compression=1
        first_args=0
        ;;
      -C|--no-compression)
        use_compression=0
        first_args=0
        ;;
      -p|--port)
        port="$1"
        shift
        first_args=0
        ;;
      -p=*|--port=*)
        port="$(echo "$arg" | sed 's/^.*=//')"
        first_args=0
        ;;
      -h|--host)
        if [ -n "$host" ]
        then
          warning "Warning: previous host ($host) ignored." "Did you forget the dot?"
        fi
        host="$1"
        shift
        first_args=0
        ;;
      -h=*|--host=*)
        if [ -n "$host" ]
        then
          warning "Warning: previous host ($host) ignored." "Did you forget the dot?"
        fi
        host="$(echo "$arg" | sed 's/^.*=//')"
        first_args=0
        ;;
      .)
        push
        first_args=0
        ;;
      -v|--verbose)
        require_first_args "$arg"
        VERBOSE=1
        QUIET=
        ;;
      -q|--quiet)
        require_first_args "$arg"
        QUIET=1
        VERBOSE=
        ;;
      -f|--fake)
        require_first_args "$arg"
        FAKE=1
        ;;
      -?|--help)
        require_first_args "$arg"
        if [ $# != 0 ]
        then
          warning "Warning: all parameters after $arg are ignored"
        fi
        print_usage
        exit 0
        ;;
      --version)
        require_first_args "$arg"
        if [ $# != 0 ]
        then
          warning "Warning: all parameters after $arg are ignored"
        fi
        echo "$VERSION"
        exit 0
        ;;
      -*)
        error "Unknown option $arg"
        print_usage | error
        exit 1
        ;;
      *)
        if [ -n "$host" ]
        then
          warning "Warning: previous host ($host) ignored." "Did you forget the dot?"
        fi
        host="$arg"
        first_args=0
        ;;
    esac
  done

  # Push if there is a remaining host
  [ -n "$host" ] && push


  if [ -z "$last_push" ]
  then
    print_usage | error
    exit 1
  fi
  exit ${last_push:-1}
}
