#! /bin/bash

# Usage
function usage
{
  echo 'Envoie la configuration sur tous les serveurs distants spécifiés'
  echo 'usage: pushrcs [-d remote-directory] [user@]remoteServer1 [user@]remoteServer2 ...'
}


# Main

localdir=""

while [ "$1" != "" ]; do
  case $1 in
    -d )                    shift
      localdir="-d $1 "
      ;;
    -h | --help )           usage
      unset localdir
      exit
      ;;
    * )                     break
      ;;
  esac
  shift
done

echo "Envoi multiple de configuration"
echo
echo

for i in $*; do
  pushrc $localdir$i
done

echo
echo
echo "Envoi de la configuration terminé"

unset localdir
