#! /bin/sh

# Grouping ensures the script not to fail when edited or overwritten
{
  COMMAND="$(which -a scp | grep -v "${GLOBALRC:-.globalrc}" | grep -v "${LOCALRC:-.localrc}" | head -1)"
  stty_conf="$(stty -g)"

  # ensure the tempfile will be deleted even if the script exits prematurely
  trap 'RCODE=$? ; rm -f "$tempfile" ; stty "$stty_conf" ; exit $RCODE' 0 1 2 3 4 6 8 15

  # Generate unique temp filename to put the configuration in
  tempfile="/tmp/sshconfig-$(id -ru)-$$-$(date +%N)"

  # temp file mustn't be visible by other users
  umask 077
  touch "$tempfile"
  chmod 600 "$tempfile" # just in case there is a problem with umask

  # Concatenate config files higher priority is given to $LOCALRC/sshconfig
  cat "$LOCALRC/sshconfig" "$GLOBALRC/sshconfig" ~/.ssh/config /etc/ssh/ssh_config > "$tempfile" 2> /dev/null

  # Execute ssh with the previous generated conf file
  command "$COMMAND" -F "$tempfile" "$@"
  RCODE="$?"

  # forward exit code
  exit $RCODE
}
