#!/bin/bash

# Places yourself in current directory
# /!\ Only works since bash 3.x /!\
pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null

# Loading Bash-specific functions
if [ -f functions ]; then
  . functions
fi

# Loading common comonents
if [ -f ../commonrc ]; then
  pushd .. > /dev/null
  . commonrc
  popd > /dev/null
fi

# Loading the prompt
if [ -f prompt ]; then
  . prompt
fi

# Coming back to precedent directory
popd > /dev/null
