#!/bin/bash

# confirm helper                                                                   
# Usage: confirm "Whould you like to continue?" [yn]                               
# if y or n is specified, it will be the default answer   
function confirm() {                                                               
    space="[y/n]"                                                                  
        if [ -n "$2" ]; then                                                       
                case "$2" in                                                       
            [yY]) space="[Y/n]" ;;                                                 
            [nN]) space="[y/N]" ;;                                                 
                esac                                                               
        fi                                                                         
                                                                                   
        while true; do                                                             
                read -n 1 -p "$1 $space " yn                                       
                                                                                   
                # default value                                                    
                if [[ "$yn" == "" && "$2" ]]; then                                 
                        yn=$2                                                      
                else                                                               
                        echo                                                       
                fi                                                                 
                                                                                   
                case $yn in                                                        
                    [Yy]*) return 0;;                                              
                    [Nn]*) return 1;;                                              
                esac                                                               
        done                                                                       
}
