#!/usr/bin/zsh

# This provides prompt highlighting

# Choose enabled modules
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Then source the script
if [ -f components/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source components/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]
fi

ZSH_HIGHLIGHT_STYLES+=(
# Main configuration (not all available options)
  unknown-token         'fg=red,bold'
  reserved-word         'fg=yellow'
  alias                 'fg=green,bold'
  builtin               'fg=green,bold'
  function              'fg=green,bold'
  command               'fg=green,bold'
  precommand            'fg=green'
  hashed-command        'fg=green'
  path                  'fg=blue,bold'
  path_prefix           'fg=blue'
  path_approx           'fg=blue,underlined'
  globbing              'fg=yellow,underlined'
  single-hyphen-option  'fg=purple,bold'
  double-hyphen-option  'fg=purple,bold'
  back-quoted-argument  'fg=purple,bold'
  default               'fg=cyan,bold' 

)
