#!/bin/zsh
# Places you into current directory
pushd $(dirname $0) > /dev/null


# Loading common components
if [ -f ../commonrc ]; then
  pushd .. > /dev/null
  source commonrc
  popd > /dev/null
fi

# RVM loading (if present)
# This is quite a bit slow on prompt startup, but I need it ...
source rvm

# Loading prompt
source prompt

# Completion initialization, should be run as late as possible
source compinit

# Conf from gmrl
source config

# zsh-syntax-highlighting, MUST stay last
source zsh-syntax-highlighting

# Comes back into previous directory
popd > /dev/null
