#!/bin/zsh
# Places you into current directory
pushd $(dirname $0) > /dev/null

# Loading common components
if [ -f ../commonrc ]; then
  pushd .. > /dev/null
  source commonrc
  popd > /dev/null
fi

# Compinit
if [ -f compinstall ]; then
  source compinstall
fi

# Conf from gmrl
if [ -f config ]; then
  source config
fi

# Loading prompt
if [ -f prompt ]; then
  source prompt
fi

# zsh-syntax-highlighting, MUST stay last
if [ -f zsh-syntax-highlighting ]; then
  source zsh-syntax-highlighting
fi

# Comes back into previous directory
popd > /dev/null
