#!/bin/bash

# Places yourself in current directory
# /!\ Only works since bash 3.x /!\
pushd "$(dirname ${BASH_SOURCE[0]})" > /dev/null

# Loading common components
source commonrc

# Loading the prompt
source bash_prompt

# Coming back to precedent directory
popd > /dev/null
