#!/bin/bash

# Places yourself in current directory
# /!\ Only works since bash 3.x /!\
pushd "$(dirname ${BASH_SOURCE[0]})" > /dev/null

# Load common components
source bazshrc.sh

# Load (compatible) functions defined as zsh-autoloadable functions
source zsh_fpath/mkcd

# Load the prompt
source bash_prompt.sh

# Come back to precedent directory
popd > /dev/null
