#!/bin/bash

# Places yourself in current directory
# /!\ Only works since bash 3.x /!\
pushd "$(dirname ${BASH_SOURCE[0]})" > /dev/null

# Disable flow control, to free C-S and C-Q
# cf https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal
stty -ixon

# Load common components
source bazshrc.sh

# Load (compatible) functions defined as zsh-autoloadable functions
source zsh_fpath/bonjour
source zsh_fpath/ff
source zsh_fpath/mkcd
source zsh_fpath/pub

# Load the prompt
source bash_prompt.sh

# Come back to precedent directory
popd > /dev/null
