#!/bin/bash

# /!\ You must already be in current directory for this to work /!\

export GLOBALRC="$(pwd -P)"

# Loading functions (we need the running_shell function)
source functions

# Login shell
if (running_shell zsh && [[ -o login ]]) || (running_shell bash && shopt -q login_shell); then
  # echo ".globalrc version" $(cat $GLOBALRC/version)
  # Display the logo
  cat logo
fi

# Testing Unicode environment
# Currently, this automatically fails on a non-amd64 arch. I should fix it. Yeah, I definitely should.
if [[ $(uname -m) = 'x86_64' ]] && scripts/unicode_test 2713 ; then
  export UNICODE_VALID=1
fi

# Disable flow control, to free C-S and C-Q
# cf https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal
stty -ixon

# Loading definitions
source definitions

# Loading aliases
source aliases
