#!/bin/bash

# /!\ You must already be in current directory for this to work /!\

# Testing Unicode environment
# Currently, this automatically fails on a non-amd64 arch. I should fix it.
if [[ $(uname -m) = 'x86_64' ]] && scripts/unicode_test 2713 ; then
  export UNICODE_VALID=1
fi

# Disable flow control, to free C-S and C-Q
# cf https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal
stty -ixon

# Loading definitions
if [ -f definitions ]; then
  source definitions
fi

# Loading functions
if [ -f functions ]; then
  source functions
fi

# Login shell
if (running_shell zsh && [[ -o login ]]) || (running_shell bash && shopt -q login_shell); then
  # echo ".globalrc version" $(cat $GLOBALRC/version)
  # Display the logo
  cat logo
fi

# Loading aliases
if [ -f aliases ]; then
  source aliases
fi
