#!/bin/sh
# This file is sourced in .profile

# .profile is sourced at graphical session startup, and the environment defined here is inherited by every forked processes
# (including shells or graphical programs)

# Use this file for configuration that is either required by graphical programs, or by the window manager itself
# Do not use it for shell-specific configuration

# Configure theme for Qt5 applications (such as vlc)
export QT_STYLE_OVERRIDE=Adwaita-Dark
