#!/bin/sh
# This file is sourced in .profile
# It MUST remain sh-compliant, because startx seems to always use sh

# .profile is sourced at graphical session startup, and the environment defined here is inherited by every forked processes
# (including shells or graphical programs)

# Use this file for configuration that is either required by graphical programs, or by the window manager itself
# Do not use it for shell-specific configuration

# Configure theme for Qt5 applications (such as vlc)
export QT_STYLE_OVERRIDE=Adwaita-Dark

# SSH-agent setup
# This code is executed only if there is no current $SSH_AUTH_SOCK, so it should be safe not to test for $DESKTOP_SESSION
# See https://unix.stackexchange.com/questions/90853/how-can-i-run-ssh-add-automatically-without-password-prompt#90869
if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  # NB: This sets up a common SSH-agent, but it doesn't automatically add your keys to it.
  # Use with ssh_config option AddKeysToAgent, to add unlocked keys automatically
fi
