#!/bin/zsh

# See https://github.com/robbyrussell/oh-my-zsh/blob/master/templates/zshrc.zsh-template
# for default zshrc loading

# location of oh-my-zsh
# TODO: Maybe something much more cleaner should be with ansible variables
ZSH="$GLOBALRC/../oh-my-zsh"

###############################################################################
# Plugins pre-configuration                                                   #
###############################################################################

### zsh-syntax-highlighting ###
# Choose enabled highlighters
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

###############################################################################

# List of plugins to load
# /!\ zsh-syntax-highlighting MUST be sourced last
plugins=(git bundler rake ruby zsh-syntax-highlighting)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

###############################################################################
# Plugins post-configuration                                                  #
###############################################################################

### zsh-syntax-highlighting ###
# Main highlight configuration (not all available options)
ZSH_HIGHLIGHT_STYLES+=(
  unknown-token         'fg=red,bold'
  reserved-word         'fg=yellow'
  alias                 'fg=green,bold'
  builtin               'fg=green,bold'
  function              'fg=green,bold'
  command               'fg=green,bold'
  precommand            'fg=green'
  hashed-command        'fg=green'
  path                  'fg=blue,bold'
  path_prefix           'fg=blue'
  path_approx           'fg=blue,underlined'
  globbing              'fg=yellow,underlined'
  single-hyphen-option  'fg=purple,bold'
  double-hyphen-option  'fg=purple,bold'
  back-quoted-argument  'fg=purple,bold'
  default               'fg=cyan,bold'
)

###############################################################################

