#!/bin/bash

# Place yourself in current folder
# /!\ Only works since bash 3.x /!\
pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null

# Chargement des composantes communes
if [ -f ../commonrc ]; then
  pushd .. > /dev/null
  . commonrc
  popd > /dev/null
fi

# Chargement du prompt
if [ -f prompt ]; then
  . prompt
fi

# Se replace dans le dossier précédent
popd > /dev/null
